### ISSUE TITLE
Abs

### ISSUE THREAD

**Issue by mrrobrob** [samseedsamseed/CodinGameTemperatures#1]
You probably want to use Math.Abs, but as you aren't using it and need it several times you should write your own function instead.

https://github.com/samseedsamseed/CodinGameTemperatures/blob/e355e1cb0b2d7450e1886a9212846eaba42575d8/CodinGameTemperatures1.0#L27

**Comment by samseedsamseed** [comment]
Okay, will do.

**Comment by samseedsamseed** [comment]
I tried to make a function version, but alas, it doesn't work. Hmm.

**Comment by mrrobrob** [comment]
In your code version that is working you're using:

Math.Sqrt(best * best)

to work out Abs.

You should move this into a function and make it work, THEN start changing it. Try to do one thing at a time because it'll make it easier to see what isn't working.

**Comment by samseedsamseed** [comment]
It works now. Whoop whoop! Your advice worked.

Also I worked out how to make Visual Studio helpful. I was using it as a glorified notepad before XD
